apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timber-frontend
  template:
    metadata:
      labels:
        app: timber-frontend
    spec:
      containers:
      - name: timber-frontend
        image: eu.gcr.io/container-solutions-workshops/timber/frontend:v1.0
        ports:
        - containerPort: 8080
        env:
          - {name: TIMBER_BACKEND_API_URL, value: "http://timber-backend:8080"}
